## 
## Cadence First Encounter "v08.10-p004_1 ((32bit) 11/04/2008 14:34 (Linux 2.6))"
## Wed Oct  7 13:28:02 2026
## 
set sdc_version 1.4
current_design System_TOP
create_clock [get_ports {UART_CLK}]  -name UART_CLK -period 271.267 -waveform {0 135.633}
set_clock_transition  -rise -min 0.05 [get_clocks {UART_CLK}]
set_clock_transition  -rise -max 0.05 [get_clocks {UART_CLK}]
set_clock_transition  -fall -min 0.05 [get_clocks {UART_CLK}]
set_clock_transition  -fall -max 0.05 [get_clocks {UART_CLK}]
create_clock [get_ports {scan_clk}]  -name scan_clk -period 100 -waveform {0 50}
set_clock_transition  -rise -min 0.05 [get_clocks {scan_clk}]
set_clock_transition  -rise -max 0.05 [get_clocks {scan_clk}]
set_clock_transition  -fall -min 0.05 [get_clocks {scan_clk}]
set_clock_transition  -fall -max 0.05 [get_clocks {scan_clk}]
create_clock [get_ports {REF_CLK}]  -name REF_CLK -period 20 -waveform {0 10}
set_clock_transition  -rise -min 0.05 [get_clocks {REF_CLK}]
set_clock_transition  -rise -max 0.05 [get_clocks {REF_CLK}]
set_clock_transition  -fall -min 0.05 [get_clocks {REF_CLK}]
set_clock_transition  -fall -max 0.05 [get_clocks {REF_CLK}]
create_generated_clock -name RX_CLK -source [get_ports {UART_CLK}] -divide_by 1 -master_clock [get_clocks {UART_CLK}] -add [get_pins {Domain_2_TOP_U1/ClkDiv_U2_RX/U17/Y}]
create_generated_clock -name TX_CLK -source [get_ports {UART_CLK}] -divide_by 32 -master_clock [get_clocks {UART_CLK}] -add [get_pins {Domain_2_TOP_U1/ClkDiv_U1_TX/U17/Y}]
set_propagated_clock  [get_ports {UART_CLK}]
set_propagated_clock  [get_pins {Domain_2_TOP_U1/ClkDiv_U2_RX/U17/Y}]
set_propagated_clock  [get_ports {scan_clk}]
set_propagated_clock  [get_ports {REF_CLK}]
set_propagated_clock  [get_pins {Domain_2_TOP_U1/ClkDiv_U1_TX/U17/Y}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {UART_RX_IN}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {UART_RX_IN}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {UART_RX_IN}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {UART_RX_IN}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {SE}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {SI[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {SI[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {SI[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -min -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -min -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -rise -max -pin Y -from_pin A [get_ports {SI[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -fall -max -pin Y -from_pin A [get_ports {SI[0]}]
set_load -pin_load -max  0.1  [get_ports {SO[3]}]
set_load -pin_load -min  0.1  [get_ports {SO[3]}]
set_load -pin_load -max  0.1  [get_ports {SO[2]}]
set_load -pin_load -min  0.1  [get_ports {SO[2]}]
set_load -pin_load -max  0.1  [get_ports {SO[1]}]
set_load -pin_load -min  0.1  [get_ports {SO[1]}]
set_load -pin_load -max  0.1  [get_ports {SO[0]}]
set_load -pin_load -min  0.1  [get_ports {SO[0]}]
set_load -pin_load -max  0.1  [get_ports {UART_TX_O}]
set_load -pin_load -min  0.1  [get_ports {UART_TX_O}]
set_load -pin_load -max  0.1  [get_ports {parity_error}]
set_load -pin_load -min  0.1  [get_ports {parity_error}]
set_load -pin_load -max  0.1  [get_ports {framing_error}]
set_load -pin_load -min  0.1  [get_ports {framing_error}]
set_case_analysis 1 [get_pins {Domain_2_TOP_U1/ClkDiv_U2_RX/i_div_ratio[0]}]
set_case_analysis 0 [get_pins {Domain_2_TOP_U1/ClkDiv_U1_TX/i_div_ratio[2]}]
set_case_analysis 0 [get_pins {Domain_2_TOP_U1/ClkDiv_U2_RX/i_div_ratio[7]}]
set_case_analysis 0 [get_pins {Domain_2_TOP_U1/ClkDiv_U2_RX/i_div_ratio[1]}]
set_case_analysis 1 [get_pins {Domain_2_TOP_U1/ClkDiv_U2_RX/i_clk_en}]
set_case_analysis 0 [get_pins {Domain_2_TOP_U1/ClkDiv_U1_TX/i_div_ratio[3]}]
set_case_analysis 0 [get_pins {Domain_2_TOP_U1/ClkDiv_U2_RX/i_div_ratio[2]}]
set_case_analysis 1 [get_pins {Domain_2_TOP_U1/ClkDiv_U1_TX/i_clk_en}]
set_case_analysis 0 [get_pins {Domain_2_TOP_U1/ClkDiv_U1_TX/i_div_ratio[4]}]
set_case_analysis 0 [get_pins {Domain_2_TOP_U1/ClkDiv_U2_RX/i_div_ratio[3]}]
set_case_analysis 1 [get_pins {Domain_2_TOP_U1/ClkDiv_U1_TX/i_div_ratio[5]}]
set_case_analysis 0 [get_pins {Domain_2_TOP_U1/ClkDiv_U2_RX/i_div_ratio[4]}]
set_case_analysis 0 [get_pins {Domain_2_TOP_U1/ClkDiv_U1_TX/i_div_ratio[6]}]
set_case_analysis 0 [get_ports {SE}]
set_case_analysis 0 [get_pins {Domain_2_TOP_U1/ClkDiv_U1_TX/i_div_ratio[0]}]
set_case_analysis 1 [get_ports {test_mode}]
set_case_analysis 0 [get_pins {Domain_2_TOP_U1/ClkDiv_U2_RX/i_div_ratio[5]}]
set_case_analysis 0 [get_pins {Domain_2_TOP_U1/ClkDiv_U1_TX/i_div_ratio[7]}]
set_case_analysis 0 [get_pins {Domain_2_TOP_U1/ClkDiv_U1_TX/i_div_ratio[1]}]
set_case_analysis 0 [get_pins {Domain_2_TOP_U1/ClkDiv_U2_RX/i_div_ratio[6]}]
set_input_delay -add_delay 54.2534 -clock [get_clocks {UART_CLK}] [get_ports {UART_RX_IN}]
set_output_delay -add_delay 54.2534 -clock [get_clocks {UART_CLK}] [get_ports {parity_error}]
set_output_delay -add_delay 54.2534 -clock [get_clocks {UART_CLK}] [get_ports {UART_TX_O}]
set_output_delay -add_delay 54.2534 -clock [get_clocks {UART_CLK}] [get_ports {framing_error}]
set_clock_uncertainty 0.1 -hold [get_clocks {scan_clk}]
set_clock_uncertainty 0.2 -setup [get_clocks {scan_clk}]
set_clock_uncertainty 0.1 -hold [get_clocks {UART_CLK}]
set_clock_uncertainty 0.2 -setup [get_clocks {UART_CLK}]
set_clock_uncertainty 0.1 -hold [get_clocks {REF_CLK}]
set_clock_uncertainty 0.2 -setup [get_clocks {REF_CLK}]
set_max_delay 40  -from [get_pins {DATA_SYNC_U2/U10/A0 DATA_SYNC_U2/U8/A0 DATA_SYNC_U2/U7/A0 DATA_SYNC_U2/U5/A0 DATA_SYNC_U2/U11/A0 DATA_SYNC_U2/U12/A0 DATA_SYNC_U2/U9/A0 DATA_SYNC_U2/U6/A0}]  -to [get_pins {Domain_1_TOP_U0/SYS_CTRL_U3/U188/A Domain_1_TOP_U0/SYS_CTRL_U3/U189/A Domain_1_TOP_U0/SYS_CTRL_U3/U157/A Domain_1_TOP_U0/SYS_CTRL_U3/U191/A Domain_1_TOP_U0/SYS_CTRL_U3/U189/C Domain_1_TOP_U0/SYS_CTRL_U3/U193/A Domain_1_TOP_U0/SYS_CTRL_U3/U161/B Domain_1_TOP_U0/SYS_CTRL_U3/U187/A Domain_1_TOP_U0/SYS_CTRL_U3/U190/A Domain_1_TOP_U0/SYS_CTRL_U3/U159/A1 Domain_1_TOP_U0/SYS_CTRL_U3/U161/C Domain_1_TOP_U0/SYS_CTRL_U3/U116/C Domain_1_TOP_U0/SYS_CTRL_U3/U157/B Domain_1_TOP_U0/SYS_CTRL_U3/U157/C Domain_1_TOP_U0/SYS_CTRL_U3/U116/A Domain_1_TOP_U0/SYS_CTRL_U3/U185/A Domain_1_TOP_U0/SYS_CTRL_U3/U184/C Domain_1_TOP_U0/SYS_CTRL_U3/U184/D Domain_1_TOP_U0/SYS_CTRL_U3/U192/A Domain_1_TOP_U0/SYS_CTRL_U3/U186/A {Domain_1_TOP_U0/ALU_U1/ALU_OUT_reg[0]/SI}}] 
set_clock_groups -name UART_CLK_1 -asynchronous  -group  [get_clocks {TX_CLK RX_CLK UART_CLK}] -group  [get_clocks {REF_CLK}]
set_clock_groups -name scan_clk_1 -physically_exclusive  -group  [get_clocks {scan_clk}] -group  [get_clocks {REF_CLK}]
set_clock_groups -name scan_clk_2 -physically_exclusive  -group  [get_clocks {scan_clk}] -group  [get_clocks {UART_CLK}]
set_clock_groups -name scan_clk_3 -physically_exclusive  -group  [get_clocks {scan_clk}] -group  [get_clocks {RX_CLK}]
set_clock_groups -name scan_clk_4 -physically_exclusive  -group  [get_clocks {scan_clk}] -group  [get_clocks {TX_CLK}]
